### PR TITLE
Add Miniobucket composition function

### PR DESCRIPTION
**Pull request by Kidswiss**
## Summary

This composition function will create:
    
* a bucket
* a policy
* a user
    
The policy is then assigned to the user and only allows that user to access exactly that bucket.

## Checklist

- [x] Categorize the PR by setting a good title and adding one of the labels:
      `bug`, `enhancement`, `documentation`, `change`, `breaking`, `dependency`
      as they show up in the changelog
- [x] Update tests.
- [x] Link this PR to related issues.

### CODE REVIEW

**Review by zugao — APPROVED** [review]
LGTM bu I haven't tested it

**Comment by Kidswiss** [comment]
> LGTM bu I haven't tested it

Yeah I just found out that the maintenance tests broke after all those dependency updates. I'm debugging that now. Maybe it uncovered a new race condition in the test...

**Comment by Kidswiss** [comment]
@zugao could you have a look at `maintenance/postgresql_test.go`? I had to kick it quite a bit for the tests to work again.

Also I refactored it a bit, it silently dropped errors before, which made debugging this a lot harder.

**Comment by Kidswiss** [comment]
> Any reason why you are paniking and not returning errors? Is it due to the goroutine?

I found two reasons:

1. yes because of the go routine, the previous version just returned the errors, but they were actually never handled.
2. if anything goes wrong in that function without panicking it will just be stuck and run into the timeout.

**Pull request merged**
