### PR TITLE
Improve PostgreSQL ordering, reduce issues

### PR DESCRIPTION
**Pull request by wejdross**
Fix probably a bug in our ObjectStorage spec

## Checklist

- [x] Categorize the PR by setting a good title and adding one of the labels:
      `bug`, `enhancement`, `documentation`, `change`, `breaking`, `dependency`
      as they show up in the changelog
- [ ] Update tests.
- [ ] Link this PR to related issues.

### CODE REVIEW

**Comment by wejdross** [comment]
@Kidswiss please take a look at this, seems that it was the issue with our services - causing broken deployment of services. After deleting that line everything seems to work.

**Comment by Kidswiss** [comment]
Can you elaborate what "probably a bug" you're fixing here?

**Comment by wejdross** [comment]
Was our intention to add this .spec.parameters.security to ObjectBuckets? I'd say no - so it's bug, but I can be wrong and miss some information - therefore "probably a bug" :laughing:

**Comment by Kidswiss** [comment]
> Was our intention to add this .spec.parameters.security to ObjectBuckets? I'd say no - so it's bug, but I can be wrong and miss some information - therefore "probably a bug" 😆

`.spec.parameters.security` contains the deletion protection settings for the bucket. They are necessary or they can't delete the buckets anymore, if they use ObjectBucket directly.

**Review by Kidswiss — APPROVED** [review]
Please test on lab, so we're sure it doesn't remove any existing sgclusters.

**Comment by zugao** [comment]
Does this PR help with creating 5 or more instances at the same time?

**Comment by wejdross** [comment]
> Does this PR help with creating 5 or more instances at the same time?

yes, it solves the issue

**Review by zugao — APPROVED** [review]
LGTM, again as Simon said, please test with existing buckets, we don't want those buckets to be removed accidentely.

**Pull request merged**
